apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Namespace }}
  ports:
  - port: 8080
    targetPort: 8080
